docker run -d --shm-size="500m" --cpuset-cpus="0" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_4x4.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="1" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_4x4.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="2" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_4x4.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="3" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_4x4.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="4" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_4x4.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="5" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_4x4.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="6" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_4x4.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="7" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_4x4.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="8" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="9" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="10" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="11" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="12" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_10x10.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="13" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_10x10.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="14" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_10x10.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="15" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_10x10.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="16" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_10x10.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="17" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_10x10.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="18" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_10x10.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="19" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_10x10.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="20" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="21" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="22" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="23" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="24" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_16x16.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="25" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_16x16.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="26" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_16x16.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="27" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_16x16.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="28" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_16x16.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="29" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_16x16.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="30" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_16x16.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="31" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_16x16.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="32" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="33" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="34" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="35" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="36" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_24x24.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="37" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_24x24.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="38" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_24x24.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="39" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_24x24.py --exp-name ppo --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="0" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_24x24.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="1" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_24x24.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="2" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_24x24.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="3" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_adj_24x24.py --exp-name ppo_no_adj --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="4" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="5" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="6" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="7" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="8" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="9" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="10" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="11" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="12" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="13" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="14" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="15" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="16" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="17" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="18" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="19" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="20" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="21" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="22" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="23" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.01 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="24" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="25" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="26" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="27" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="28" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="29" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="30" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="31" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="32" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="33" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="34" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="35" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="36" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="37" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="38" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="39" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -0.1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="0" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="1" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="2" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="3" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_4x4.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining4x4F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="4" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="5" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="6" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="7" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_10x10.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining10x10F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="8" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="9" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="10" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="11" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_16x16.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining16x16F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 4
docker run -d --shm-size="500m" --cpuset-cpus="12" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 1
docker run -d --shm-size="500m" --cpuset-cpus="13" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 2
docker run -d --shm-size="500m" --cpuset-cpus="14" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 3
docker run -d --shm-size="500m" --cpuset-cpus="15" -e WANDB=123 invalid_action_masking:latest python invalid_action_masking/ppo_no_mask_24x24.py --exp-name ppo_no_mask --total-timesteps 500000 --wandb-project-name invalid_action_masking --gym-id MicrortsMining24x24F9-v0 --no-cuda --gae --norm-obs --norm-adv --anneal-lr --clip-vloss --invalid-action-penalty -1 --prod-mode --capture-video --seed 4
